spring:
  datasource:
    url: jdbc:mysql://${testDbIp:127.0.0.1}:3306/app20220916_2__test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${testDbId:root}
    password: ${testDbPw:}
  jpa:
    hibernate:
      ddl-auto: none

