spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app10?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none

